# Generated by Django 3.2.12 on 2022-04-07 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Username')),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='Password')),
                ('email', models.EmailField(max_length=64, verbose_name='Email')),
            ],
        ),
    ]
