# Generated by Django 3.2.12 on 2022-04-29 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=5, verbose_name='FIPS')),
                ('interval', models.CharField(max_length=7, verbose_name='Interval')),
                ('coverage', models.IntegerField(verbose_name='Coverage')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('prediction', models.IntegerField(verbose_name='Prediction')),
                ('price', models.FloatField(verbose_name='Price')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weather.user')),
            ],
        ),
    ]
