# Generated by Django 3.2.12 on 2022-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.CharField(max_length=5)),
                ('longitude', models.CharField(max_length=128)),
                ('latitude', models.CharField(max_length=128)),
            ],
        ),
    ]
